[package]
name = "rust-bin-packing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
fs = "0.0.5"
pack_it_up = "1.0.0"
walkdir = "2.5.0"
